<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM1cdFLF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM1cdFLF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM1cdFLF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM1cdFLF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM1cdFLF\App_KernelDevDebugContainer([
    'container.build_hash' => 'M1cdFLF',
    'container.build_id' => '99e635e5',
    'container.build_time' => 1660214026,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM1cdFLF');
