<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1WOKu10\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1WOKu10/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1WOKu10.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1WOKu10\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1WOKu10\App_KernelDevDebugContainer([
    'container.build_hash' => '1WOKu10',
    'container.build_id' => '3986944c',
    'container.build_time' => 1660681177,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1WOKu10');
